# Generated by Django 3.0.4 on 2020-06-27 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0048_auto_20200627_1423'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name': 'Image', 'verbose_name_plural': 'Images'},
        ),
    ]
