# Generated by Django 3.0.4 on 2020-06-08 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShopCartForm',
        ),
    ]
