# Generated by Django 3.0.4 on 2020-06-12 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0029_auto_20200612_1716'),
        ('order', '0002_delete_shopcartform'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcart',
            name='slug',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_slug', to='product.Product'),
        ),
    ]
