# Generated by Django 3.0.4 on 2020-06-12 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_shopcart_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopcart',
            name='slug',
            field=models.SlugField(default=0),
            preserve_default=False,
        ),
    ]
